### ISSUE TITLE
Missing Checkout Option After Adding Tokens to Cart

### ISSUE THREAD

**Issue by minjja** [jacksturt/cherry-nft-mint-website#7]
It appears that there is functionality to add tokens to the cart, but I am unable to find a checkout option anywhere in the interface.

Questions:
Is there supposed to be a checkout option available?
If not, do we actually need this cart functionality, or should it be removed?

![Screenshot (17)](https://github.com/user-attachments/assets/c43a43db-4447-4e73-a55c-406afb70e948)

**Comment by jacksturt** [comment]
Fixed this, should not be a cart and changed these instead to the same buttons on the other pages.

**Comment by minjja** [comment]
Thanks
